controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /home
    controller: App\Controller\HomeController::index

etudiant:
    path: /liste_etudiant
    controller: App\Controller\ListeEtudiantController::index

professeur:
    path: /liste_professeur
    controller: App\Controller\ListeProfesseurController::index